### ISSUE TITLE
map[string]interface{} type for DATASETS

### ISSUE THREAD

**Issue by ghost** [egomobile/httpcache#2]
Data type should be `map[string]interface{}` to reduce memory usage a little bit:

https://github.com/egomobile/httpcache/blob/e65703ad87a2550ce48739efe9160679f3f8f8fb/httpcache.go#L17

**Comment by ekmobile** [comment]
![Bildschirm­foto 2023-02-09 um 09 51 41](https://user-images.githubusercontent.com/37370194/217763085-abf9bf0e-e92f-4697-a1bd-2145efd16f03.png)

**Comment by ekmobile** [comment]
@mkloubertego

**Comment by ghost** [comment]
try this, @ekmobile 

```golang
var DATASETS = make(map[string]interface{})
```

**Comment by ghost** [comment]
or add additional `{}`, because `interface{}` is the type

**Comment by ghost** [comment]
as discussed, I close this here @ekmobile 

this might not bring so much benefits, I guess
